Move include of geocoder.h to before it's needed
The Nominatim unit tests declare some functions from nominatim.c that
take a "struct geocode_results_list *" as argument, but "struct
geocode_results_list" was not declared before those lines.

We've been seeing *warnings* about this of the form:
```
../../Xastir/tests/test_nominatim.c:59:84: warning: 'struct geocode_result_list' declared inside parameter list will not be visible outside of this definition or declaration
```

in CI testing for a while but since the code ran just fine, we didn't
pay attention.  We should have.  When Xastir is built with gcc14
instead of gcc13, this warning means something, because later we get
this *error* in compiling the nominatim tests:

```
../../Xastir/tests/test_nominatim.c:148:50: error: passing argument 3 of 'cache_lookup' from incompatible pointer type [-Wincompatible-pointer-types]
  148 |     int found = cache_lookup("Test Query", NULL, &results);
      |                                                  ^~~~~~~~
      |                                                  |
      |                                                  struct geocode_result_list *
../../Xastir/tests/test_nominatim.c:58:99: note: expected 'struct geocode_result_list *' but argument is of type 'struct geocode_result_list *'
   58 | extern int cache_lookup(const char *query, const char *country_codes, struct geocode_result_list *results);
      |                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

The entire reason for the error is that "geocoder.h", where
geocode_results_list is declared, was being included *after* the lines
of code that made use of the struct.

Moving that include to *before* the use of its contents gets rid of
the warnings *and* the error.